/**
 * TAROT_DECK — Complete 78-card Rider-Waite-Smith tarot dataset for Lumina.
 *
 * Contains the 22 Major Arcana and 56 Minor Arcana (14 each of Wands, Cups,
 * Swords, Pentacles). Each entry carries authentic Rider-Waite symbolism,
 * astrological / elemental / numerological correspondences, upright & reversed
 * meanings, yes/no tendencies, an affirmation, a unicode symbol, and
 * intention tags drawn from a controlled vocabulary used by Lumina's
 * auto-frequency feature.
 *
 * Side-effect free: safe to import from both server and client components.
 *
 * @packageDocumentation
 */

export type TarotCard = {
  id: string;
  number: number;
  arcana: "major" | "minor";
  suit: "major" | "wands" | "cups" | "swords" | "pentacles";
  name: string;
  nameShort: string;
  element?: string;
  astrology?: string;
  numerology?: string;
  keywordsUpright: string[];
  keywordsReversed: string[];
  meaningUpright: string;
  meaningReversed: string;
  yesNoUpright: "yes" | "no" | "maybe";
  yesNoReversed: "yes" | "no" | "maybe";
  affirmation: string;
  symbol: string;
  intentionTags: string[];
};

export const TAROT_DECK: TarotCard[] = [
  // ============================================================
  // MAJOR ARCANA (0–21)
  // ============================================================
  {
    id: "the-fool",
    number: 0,
    arcana: "major",
    suit: "major",
    name: "The Fool",
    nameShort: "Fool",
    element: "Air",
    astrology: "Uranus",
    numerology: "Zero — pure potential, the void from which all begins.",
    keywordsUpright: ["new beginnings", "innocence", "spontaneity", "free spirit", "leap of faith"],
    keywordsReversed: ["recklessness", "naivety", "risk", "poor choices", "held back"],
    meaningUpright:
      "A new journey beckons, and you stand at the cliff's edge with the lightness of a child. The Fool invites you to trust the unknown, release the need for certainty, and step forward with wonder. Magic lives in the beginner's mind.",
    meaningReversed:
      "Reversed, the Fool warns of recklessness or a reluctance to begin. You may be ignoring warning signs or staying frozen at the edge. Pause, gather wisdom, then choose your next step consciously.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I trust the path before me and welcome new beginnings with an open heart.",
    symbol: "🌠",
    intentionTags: ["new-beginnings", "courage", "travel"],
  },
  {
    id: "the-magician",
    number: 1,
    arcana: "major",
    suit: "major",
    name: "The Magician",
    nameShort: "Magician",
    element: "Air",
    astrology: "Mercury",
    numerology: "One — unity, will, the spark of manifestation.",
    keywordsUpright: ["manifestation", "willpower", "resourcefulness", "skill", "action"],
    keywordsReversed: ["manipulation", "untapped talents", "deception", "lack of focus"],
    meaningUpright:
      "As above, so below: the Magician channels divine will into the material world through focused intention. You have all the tools you need — earth, air, fire, water — at your command. Now is the time to act and manifest.",
    meaningReversed:
      "Reversed, the Magician suggests manipulation, untapped gifts, or wasted talent. Power without integrity becomes trickery. Realign your will with your highest truth.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I have all I need to manifest my highest vision.",
    symbol: "♾",
    intentionTags: ["creativity", "career", "abundance"],
  },
  {
    id: "the-high-priestess",
    number: 2,
    arcana: "major",
    suit: "major",
    name: "The High Priestess",
    nameShort: "High Priestess",
    element: "Water",
    astrology: "Moon",
    numerology: "Two — duality, intuition, the veil between worlds.",
    keywordsUpright: ["intuition", "mystery", "subconscious", "inner voice", "stillness"],
    keywordsReversed: ["secrets", "disconnection", "withdrawal", "repressed intuition"],
    meaningUpright:
      "Veiled between the pillars of light and dark, the High Priestess guards the threshold of the unconscious. She invites you to listen inward, where moonlit wisdom waits. What you seek is not outside — it is within.",
    meaningReversed:
      "Reversed, she signals ignored intuition or secrets surfacing uncomfortably. You may be out of touch with your inner voice or hiding the truth from yourself. Quiet the noise and listen again.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I trust the quiet wisdom rising within me.",
    symbol: "☽",
    intentionTags: ["intuition", "spiritual-growth", "truth"],
  },
  {
    id: "the-empress",
    number: 3,
    arcana: "major",
    suit: "major",
    name: "The Empress",
    nameShort: "Empress",
    element: "Earth",
    astrology: "Venus",
    numerology: "Three — creation, growth, abundance, the mother.",
    keywordsUpright: ["abundance", "nurturing", "fertility", "nature", "sensuality"],
    keywordsReversed: ["smothering", "dependence", "creative block", "neglect"],
    meaningUpright:
      "The Empress is the great mother — abundant, creative, and deeply rooted in nature's rhythms. She blesses your endeavors with fertility, beauty, and sensual pleasure. Receive her gifts and tend what is growing.",
    meaningReversed:
      "Reversed, the Empress points to overprotection, neglect, or a blocked creative flow. Examine where you give too much — or too little — to yourself and others. Restore balance to receive freely again.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I am a vessel of abundance, creativity, and nurturing love.",
    symbol: "♀",
    intentionTags: ["abundance", "creativity", "family"],
  },
  {
    id: "the-emperor",
    number: 4,
    arcana: "major",
    suit: "major",
    name: "The Emperor",
    nameShort: "Emperor",
    element: "Fire",
    astrology: "Aries",
    numerology: "Four — structure, stability, foundation, the father.",
    keywordsUpright: ["authority", "structure", "leadership", "stability", "discipline"],
    keywordsReversed: ["domination", "rigidity", "control", "weakness"],
    meaningUpright:
      "The Emperor rules with steady authority, building kingdoms on order and discipline. He invites you to claim your sovereignty, set boundaries, and create structures that endure. Power rooted in wisdom serves all.",
    meaningReversed:
      "Reversed, the Emperor warns of tyranny, inflexibility, or the abuse of power — either your own or another's. Soften control where it has become brittle; rebuild on firmer, fairer ground.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I lead my life with wisdom, structure, and steady strength.",
    symbol: "♈",
    intentionTags: ["career", "protection", "courage"],
  },
  {
    id: "the-hierophant",
    number: 5,
    arcana: "major",
    suit: "major",
    name: "The Hierophant",
    nameShort: "Hierophant",
    element: "Earth",
    astrology: "Taurus",
    numerology: "Five — tradition, teaching, the bridge of belief.",
    keywordsUpright: ["tradition", "spiritual wisdom", "conformity", "guidance", "belief"],
    keywordsReversed: ["rebellion", "nonconformity", "new methods", "freedom"],
    meaningUpright:
      "The Hierophant bridges heaven and earth, keeper of sacred teachings and inherited tradition. He invites you to learn from those who came before — or to teach what you have mastered. Honor lineage even as you evolve.",
    meaningReversed:
      "Reversed, the Hierophant signals rebellion against convention or a path beyond established dogma. Trust your own interpretation. New ways are calling.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I honor wisdom's lineage while trusting my own truth.",
    symbol: "♰",
    intentionTags: ["spiritual-growth", "truth", "healing"],
  },
  {
    id: "the-lovers",
    number: 6,
    arcana: "major",
    suit: "major",
    name: "The Lovers",
    nameShort: "Lovers",
    element: "Air",
    astrology: "Gemini",
    numerology: "Six — harmony, choice, sacred union.",
    keywordsUpright: ["love", "harmony", "choice", "union", "values"],
    keywordsReversed: ["disharmony", "imbalance", "misalignment", "poor choices"],
    meaningUpright:
      "Under the blessing of Raphael, two souls stand in conscious union — a choice aligned with values, not just desire. The Lovers invite you to merge with what truly reflects your heart. Choose love, choose truth, choose yourself.",
    meaningReversed:
      "Reversed, the Lovers reveal misalignment, broken trust, or a choice out of step with your values. Examine the relationships and decisions that no longer fit. Realignment begins with honesty.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I choose love and union that align with my deepest values.",
    symbol: "❤️",
    intentionTags: ["love", "truth", "family"],
  },
  {
    id: "the-chariot",
    number: 7,
    arcana: "major",
    suit: "major",
    name: "The Chariot",
    nameShort: "Chariot",
    element: "Water",
    astrology: "Cancer",
    numerology: "Seven — mastery, focus, victory through will.",
    keywordsUpright: ["determination", "victory", "willpower", "control", "direction"],
    keywordsReversed: ["lack of direction", "aggression", "scattered focus", "defeat"],
    meaningUpright:
      "The Charioteer drives opposing forces into a single direction through will and focus. Victory comes not by luck but by mastery of the inner horses. Move forward with resolve — you will arrive.",
    meaningReversed:
      "Reversed, the Chariot signals scattered energy, impulsiveness, or a stalled plan. Regain the reins before momentum is lost. Define the destination before driving harder.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I direct my will with focus and claim my victory.",
    symbol: "⚔️",
    intentionTags: ["courage", "career", "travel"],
  },
  {
    id: "strength",
    number: 8,
    arcana: "major",
    suit: "major",
    name: "Strength",
    nameShort: "Strength",
    element: "Fire",
    astrology: "Leo",
    numerology: "Eight — inner power, courage, infinite patience.",
    keywordsUpright: ["courage", "inner strength", "patience", "compassion", "taming"],
    keywordsReversed: ["self-doubt", "weakness", "raw emotion", "insecurity"],
    meaningUpright:
      "With infinite patience and gentle hands, the maiden tames the lion — true strength is not force but love. Meet your wildness with compassion, and it becomes your ally. Soft power prevails.",
    meaningReversed:
      "Reversed, Strength reveals self-doubt, suppressed instinct, or courage faltering. The lion within needs tending, not silencing. Reclaim your gentle authority.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I meet my strength and my shadows with compassion.",
    symbol: "∞",
    intentionTags: ["courage", "healing", "protection"],
  },
  {
    id: "the-hermit",
    number: 9,
    arcana: "major",
    suit: "major",
    name: "The Hermit",
    nameShort: "Hermit",
    element: "Earth",
    astrology: "Virgo",
    numerology: "Nine — solitude, wisdom, the inner lantern.",
    keywordsUpright: ["introspection", "solitude", "inner guidance", "wisdom", "seeking"],
    keywordsReversed: ["isolation", "loneliness", "withdrawal", "lost"],
    meaningUpright:
      "The Hermit lifts his lantern on the inner mountain, seeking truth no outer light can give. He invites you to withdraw, reflect, and follow your own quiet glow. The answer waits in stillness.",
    meaningReversed:
      "Reversed, the Hermit warns of isolation, avoidance, or losing your way in withdrawal. Solitude becomes exile when it hides you from life. Reconnect when ready.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I follow the quiet lantern of my inner truth.",
    symbol: "🪔",
    intentionTags: ["spiritual-growth", "intuition", "clarity"],
  },
  {
    id: "wheel-of-fortune",
    number: 10,
    arcana: "major",
    suit: "major",
    name: "Wheel of Fortune",
    nameShort: "Wheel",
    element: "Fire",
    astrology: "Jupiter",
    numerology: "Ten — cycle, return, the turning of fate.",
    keywordsUpright: ["cycles", "destiny", "change", "luck", "turning point"],
    keywordsReversed: ["resistance", "bad luck", "setbacks", "loss of control"],
    meaningUpright:
      "The great wheel turns — what was up shall descend, what was low shall rise. You stand at a turning point orchestrated by forces larger than your will. Flow with the cycle; fortune favors the ready.",
    meaningReversed:
      "Reversed, the Wheel signals setbacks, resistance, or a turn against you. The cycle still turns — your work is to release what is ending and prepare for the next ascent.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I move with life's cycles and trust the turning of fortune.",
    symbol: "☸",
    intentionTags: ["transformation", "abundance", "release"],
  },
  {
    id: "justice",
    number: 11,
    arcana: "major",
    suit: "major",
    name: "Justice",
    nameShort: "Justice",
    element: "Air",
    astrology: "Libra",
    numerology: "Eleven — balance, truth, karma.",
    keywordsUpright: ["justice", "fairness", "truth", "karma", "accountability"],
    keywordsReversed: ["unfairness", "dishonesty", "avoidance", "imbalance"],
    meaningUpright:
      "Justice weighs every action with impartial precision; truth cannot be hidden from her scales. You are called to act with integrity and accept what is owed — given and received. Cause and effect find their balance.",
    meaningReversed:
      "Reversed, Justice warns of dishonesty, avoidance, or imbalance in a situation. Accountability has been dodged. Restore fairness, beginning within.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I live in alignment with truth, balance, and just cause.",
    symbol: "⚖️",
    intentionTags: ["truth", "clarity", "protection"],
  },
  {
    id: "the-hanged-man",
    number: 12,
    arcana: "major",
    suit: "major",
    name: "The Hanged Man",
    nameShort: "Hanged Man",
    element: "Water",
    astrology: "Neptune",
    numerology: "Twelve — surrender, reversal, willing sacrifice.",
    keywordsUpright: ["surrender", "new perspective", "pause", "sacrifice", "release"],
    keywordsReversed: ["stalling", "resistance", "indecision", "delay"],
    meaningUpright:
      "Suspended between heaven and earth, the Hanged Man finds revelation through surrender. Hang upside down to see the world anew — what felt like loss becomes gift. Pause, let go, receive.",
    meaningReversed:
      "Reversed, the Hanged Man signals stalling, indecision, or fighting the necessary pause. Resistance prolongs what surrender would resolve. Trust the stillness.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I surrender control and welcome a new perspective.",
    symbol: "🜨",
    intentionTags: ["release", "spiritual-growth", "clarity"],
  },
  {
    id: "death",
    number: 13,
    arcana: "major",
    suit: "major",
    name: "Death",
    nameShort: "Death",
    element: "Water",
    astrology: "Scorpio",
    numerology: "Thirteen — transformation, endings, rebirth.",
    keywordsUpright: ["transformation", "endings", "transition", "release", "rebirth"],
    keywordsReversed: ["resistance to change", "stagnation", "decay", "clinging"],
    meaningUpright:
      "Death rides not to destroy but to clear — what has ended must be honored and released so new life may rise. The old self falls away; the seed cracks open. Transformation is the only constant.",
    meaningReversed:
      "Reversed, Death signals resistance to necessary endings, prolonging stagnation. You cannot carry the dead weight forward. Allow the closure you fear.",
    yesNoUpright: "no",
    yesNoReversed: "maybe",
    affirmation: "I honor endings as sacred thresholds to new life.",
    symbol: "💀",
    intentionTags: ["transformation", "release", "healing"],
  },
  {
    id: "temperance",
    number: 14,
    arcana: "major",
    suit: "major",
    name: "Temperance",
    nameShort: "Temperance",
    element: "Fire",
    astrology: "Sagittarius",
    numerology: "Fourteen — synthesis, balance, sacred alchemy.",
    keywordsUpright: ["balance", "moderation", "patience", "alchemy", "harmony"],
    keywordsReversed: ["imbalance", "excess", "impatience", "realignment"],
    meaningUpright:
      "The angel pours fire and water into one vessel, blending opposites into a third, sacred thing. Temperance asks for patience and the middle path — true alchemy needs time. Mix with care; the elixir is forming.",
    meaningReversed:
      "Reversed, Temperance signals excess, impatience, or a life out of balance. Two elements have separated. Recalibrate gently before proceeding.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I blend all parts of myself into harmonious wholeness.",
    symbol: "⚗️",
    intentionTags: ["healing", "clarity", "spiritual-growth"],
  },
  {
    id: "the-devil",
    number: 15,
    arcana: "major",
    suit: "major",
    name: "The Devil",
    nameShort: "Devil",
    element: "Earth",
    astrology: "Capricorn",
    numerology: "Fifteen — bondage, shadow, materiality.",
    keywordsUpright: ["bondage", "attachment", "shadow", "temptation", "materialism"],
    keywordsReversed: ["release", "freedom", "reclaiming power", "detachment"],
    meaningUpright:
      "The Devil reveals the chains we forge in shadow — addiction, obsession, the lies we tell to stay comfortable. Look directly at what binds you; the chains are loose. Freedom begins with seeing.",
    meaningReversed:
      "Reversed, the Devil signals a loosening of chains, a reclaiming of power, or the slow climb out of attachment. The shadow is being integrated. Walk into the light.",
    yesNoUpright: "no",
    yesNoReversed: "yes",
    affirmation: "I release what binds me and reclaim my freedom.",
    symbol: "⛧",
    intentionTags: ["release", "healing", "truth"],
  },
  {
    id: "the-tower",
    number: 16,
    arcana: "major",
    suit: "major",
    name: "The Tower",
    nameShort: "Tower",
    element: "Fire",
    astrology: "Mars",
    numerology: "Sixteen — upheaval, awakening, sudden change.",
    keywordsUpright: ["upheaval", "revelation", "awakening", "destruction", "sudden change"],
    keywordsReversed: ["averting disaster", "fear of change", "delayed reckoning", "resistance"],
    meaningUpright:
      "Lightning splits the false tower — what was built on lies cannot stand. The Tower's destruction is brutal mercy, clearing ground for truth. Let it fall; the foundation you rebuild will be real.",
    meaningReversed:
      "Reversed, the Tower signals a delayed reckoning, an upheaval narrowly averted, or a stubborn clinging to a doomed structure. The change will come — better to meet it willingly.",
    yesNoUpright: "no",
    yesNoReversed: "maybe",
    affirmation: "I welcome truth's lightning and rebuild on solid ground.",
    symbol: "⚡",
    intentionTags: ["transformation", "release", "truth"],
  },
  {
    id: "the-star",
    number: 17,
    arcana: "major",
    suit: "major",
    name: "The Star",
    nameShort: "Star",
    element: "Air",
    astrology: "Aquarius",
    numerology: "Seventeen — hope, faith, renewal after the storm.",
    keywordsUpright: ["hope", "faith", "renewal", "inspiration", "healing"],
    keywordsReversed: ["despair", "disconnection", "lost faith", "hopelessness"],
    meaningUpright:
      "After the Tower's fall, the Star pours her waters — celestial and earthly — back into the world. Hope returns, gentle and luminous. You are guided, you are healing, you are renewed.",
    meaningReversed:
      "Reversed, the Star signals lost faith, discouragement, or disconnection from your guiding light. The well feels dry. Reach for the small star still glimmering within.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I am guided, renewed, and held by the light of hope.",
    symbol: "🌟",
    intentionTags: ["healing", "spiritual-growth", "new-beginnings"],
  },
  {
    id: "the-moon",
    number: 18,
    arcana: "major",
    suit: "major",
    name: "The Moon",
    nameShort: "Moon",
    element: "Water",
    astrology: "Pisces",
    numerology: "Eighteen — illusion, dream, the unconscious.",
    keywordsUpright: ["illusion", "intuition", "dreams", "uncertainty", "the subconscious"],
    keywordsReversed: ["clarity", "release of fear", "truth revealed", "dispelling illusion"],
    meaningUpright:
      "The Moon lights a path that twists through shadow and dream; nothing is quite as it seems. Trust intuition over reason now — but move carefully. Hidden things are stirring.",
    meaningReversed:
      "Reversed, the Moon signals illusion lifting, fears releasing, or truth emerging from the mist. What haunted you loses its power. Step into the clearing.",
    yesNoUpright: "no",
    yesNoReversed: "yes",
    affirmation: "I move through illusion with intuition as my lantern.",
    symbol: "🌙",
    intentionTags: ["intuition", "spiritual-growth", "clarity"],
  },
  {
    id: "the-sun",
    number: 19,
    arcana: "major",
    suit: "major",
    name: "The Sun",
    nameShort: "Sun",
    element: "Fire",
    astrology: "Sun",
    numerology: "Nineteen — joy, vitality, radiant success.",
    keywordsUpright: ["joy", "success", "vitality", "clarity", "abundance"],
    keywordsReversed: ["temporary gloom", "overconfidence", "delayed joy", "clouded"],
    meaningUpright:
      "The Sun blazes with the simple joy of being alive — warmth, truth, and radiant success. Whatever shadow you walked through is over. Celebrate, shine, and share your light.",
    meaningReversed:
      "Reversed, the Sun signals a temporary cloud over joy, or success delayed by doubt. The light has not gone out — it only waits for you to lift your face. Let it in.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I radiate joy, vitality, and abundant life.",
    symbol: "☀️",
    intentionTags: ["abundance", "healing", "clarity"],
  },
  {
    id: "judgement",
    number: 20,
    arcana: "major",
    suit: "major",
    name: "Judgement",
    nameShort: "Judgement",
    element: "Fire",
    astrology: "Pluto",
    numerology: "Twenty — awakening, reckoning, rebirth.",
    keywordsUpright: ["awakening", "reckoning", "rebirth", "calling", "absolution"],
    keywordsReversed: ["self-doubt", "refusal of the call", "stagnation", "harsh judgement"],
    meaningUpright:
      "The angel's trumpet calls the dead to rise — a reckoning that is also absolution. You have heard your calling; the past is forgiven. Step into the next life you have earned.",
    meaningReversed:
      "Reversed, Judgement signals self-doubt, refusal of the call, or a harsh inner critic stalling your rebirth. The trumpet still sounds. Forgive yourself and rise.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I answer my calling and rise renewed into my true life.",
    symbol: "📯",
    intentionTags: ["transformation", "spiritual-growth", "truth"],
  },
  {
    id: "the-world",
    number: 21,
    arcana: "major",
    suit: "major",
    name: "The World",
    nameShort: "World",
    element: "Earth",
    astrology: "Saturn",
    numerology: "Twenty-one — completion, wholeness, integration.",
    keywordsUpright: ["completion", "wholeness", "fulfillment", "integration", "achievement"],
    keywordsReversed: ["incompletion", "delays", "loose ends", "seeking closure"],
    meaningUpright:
      "The dancer within the wreath has completed the great cycle — every lesson integrated, every part of the self welcomed home. You arrive at wholeness. Celebrate, and prepare to begin again, wiser.",
    meaningReversed:
      "Reversed, the World signals loose ends, delays, or a cycle not yet complete. Some integration remains. Finish what waits before stepping through.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I am whole, complete, and stepping into a new cycle.",
    symbol: "🌍",
    intentionTags: ["transformation", "spiritual-growth", "abundance"],
  },

  // ============================================================
  // WANDS — Fire 🜂
  // ============================================================
  {
    id: "ace-of-wands",
    number: 1,
    arcana: "minor",
    suit: "wands",
    name: "Ace of Wands",
    nameShort: "Ace of Wands",
    element: "Fire",
    astrology: "Aries",
    numerology: "One — the spark of genesis, inspiration ignited.",
    keywordsUpright: ["inspiration", "new venture", "passion", "spark", "creation"],
    keywordsReversed: ["delays", "lack of motivation", "low energy", "false start"],
    meaningUpright:
      "A single wand bursts with living flame — the seed of inspiration, the spark of a new venture. Passion is moving through you. Seize it; act before the fire cools.",
    meaningReversed:
      "Reversed, the Ace of Wands suggests a stalled spark, low motivation, or a project that won't ignite. Tend your inner flame before pushing forward.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I honor the spark within and act on my inspiration.",
    symbol: "🜂",
    intentionTags: ["creativity", "new-beginnings", "career"],
  },
  {
    id: "two-of-wands",
    number: 2,
    arcana: "minor",
    suit: "wands",
    name: "Two of Wands",
    nameShort: "Two of Wands",
    element: "Fire",
    astrology: "Aries",
    numerology: "Two — choice, planning, the world in your hands.",
    keywordsUpright: ["planning", "decisions", "future vision", "discovery"],
    keywordsReversed: ["fear of unknown", "playing safe", "indecision", "delay"],
    meaningUpright:
      "The figure holds the world in his hands, weighing the path ahead from the safety of his castle. Vision is clear; now choose where to direct it. The future is yours to plan.",
    meaningReversed:
      "Reversed, the Two of Wands signals fear of the unknown or playing it too safe. The plan stalls because the leap feels too far. Trust your map.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I see my future clearly and choose my path with courage.",
    symbol: "🜂",
    intentionTags: ["career", "clarity", "courage"],
  },
  {
    id: "three-of-wands",
    number: 3,
    arcana: "minor",
    suit: "wands",
    name: "Three of Wands",
    nameShort: "Three of Wands",
    element: "Fire",
    astrology: "Aries",
    numerology: "Three — expansion, foresight, returns in motion.",
    keywordsUpright: ["expansion", "foresight", "progress", "waiting for results"],
    keywordsReversed: ["delays", "obstacles", "narrow vision", "frustration"],
    meaningUpright:
      "Ships return on the horizon — your plans are in motion, your investments sailing toward harbor. Wait with confidence; the work you began is bearing fruit.",
    meaningReversed:
      "Reversed, the Three of Wands signals delays, obstacles, or returns slower than hoped. Widen your view; the channel may need clearing.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I trust the slow, sure arrival of what I have set in motion.",
    symbol: "🜂",
    intentionTags: ["career", "abundance", "travel"],
  },
  {
    id: "four-of-wands",
    number: 4,
    arcana: "minor",
    suit: "wands",
    name: "Four of Wands",
    nameShort: "Four of Wands",
    element: "Fire",
    astrology: "Venus",
    numerology: "Four — stability, celebration, foundation.",
    keywordsUpright: ["celebration", "home", "harmony", "milestone", "community"],
    keywordsReversed: ["instability", "lack of support", "delayed celebration", "transition"],
    meaningUpright:
      "Garlands hang from festive pillars — a milestone reached, a homecoming earned. Gather your community and celebrate the stability you have built. Joy shared is joy multiplied.",
    meaningReversed:
      "Reversed, the Four of Wands signals shaky foundations, a delayed celebration, or a transition unsettling home. Tend the structure beneath the festivities.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I celebrate the milestones that anchor my life.",
    symbol: "🜂",
    intentionTags: ["family", "abundance", "healing"],
  },
  {
    id: "five-of-wands",
    number: 5,
    arcana: "minor",
    suit: "wands",
    name: "Five of Wands",
    nameShort: "Five of Wands",
    element: "Fire",
    astrology: "Saturn",
    numerology: "Five — conflict, challenge, friction that sharpens.",
    keywordsUpright: ["conflict", "competition", "tension", "diversity", "struggle"],
    keywordsReversed: ["resolution", "avoidance", "compromise", "inner conflict"],
    meaningUpright:
      "Five figures clash in playful but real contest — ideas, egos, and ambitions collide. Competition sharpens what complacency dulls. Find the constructive edge in the friction.",
    meaningReversed:
      "Reversed, the Five of Wands signals resolution, compromise, or a conflict avoided that still simmers. Make peace honestly, not by burying it.",
    yesNoUpright: "no",
    yesNoReversed: "maybe",
    affirmation: "I meet conflict with clarity and grow through its challenge.",
    symbol: "🜂",
    intentionTags: ["courage", "career", "clarity"],
  },
  {
    id: "six-of-wands",
    number: 6,
    arcana: "minor",
    suit: "wands",
    name: "Six of Wands",
    nameShort: "Six of Wands",
    element: "Fire",
    astrology: "Jupiter",
    numerology: "Six — victory, recognition, public praise.",
    keywordsUpright: ["victory", "recognition", "success", "public praise", "leadership"],
    keywordsReversed: ["ego", "fall from grace", "delayed recognition", "self-doubt"],
    meaningUpright:
      "The victor rides through the crowd, laurel wreath held high. Your efforts are recognized; success is public and well earned. Receive the praise with grace and humility.",
    meaningReversed:
      "Reversed, the Six of Wands warns of ego inflation, falling from favor, or recognition that slips through your fingers. Check where pride has overtaken substance.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I receive recognition with grace and stay rooted in service.",
    symbol: "🜂",
    intentionTags: ["career", "courage", "abundance"],
  },
  {
    id: "seven-of-wands",
    number: 7,
    arcana: "minor",
    suit: "wands",
    name: "Seven of Wands",
    nameShort: "Seven of Wands",
    element: "Fire",
    astrology: "Mars",
    numerology: "Seven — defense, conviction, holding the high ground.",
    keywordsUpright: ["defense", "perseverance", "standing your ground", "conviction"],
    keywordsReversed: ["overwhelm", "yielding", "exhaustion", "giving up"],
    meaningUpright:
      "One figure holds the high ground against many — your position is challenged but defensible. Hold your ground with conviction; the advantage is yours if you do not tire.",
    meaningReversed:
      "Reversed, the Seven of Wands signals exhaustion, overwhelm, or yielding what you should defend. Step back, regroup, then choose your battles with care.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I stand firmly in my truth, even when challenged.",
    symbol: "🜂",
    intentionTags: ["protection", "courage", "truth"],
  },
  {
    id: "eight-of-wands",
    number: 8,
    arcana: "minor",
    suit: "wands",
    name: "Eight of Wands",
    nameShort: "Eight of Wands",
    element: "Fire",
    astrology: "Mercury",
    numerology: "Eight — momentum, swift movement, communication.",
    keywordsUpright: ["speed", "movement", "communication", "momentum", "swift change"],
    keywordsReversed: ["delays", "frustration", "resistance", "miscommunication"],
    meaningUpright:
      "Eight wands arc through clear sky — a sudden burst of momentum, messages flying, plans accelerating. What was stalled now moves fast. Stay loose and follow the flow.",
    meaningReversed:
      "Reversed, the Eight of Wands signals delays, miscommunication, or momentum blocked. Resistance is temporary. Recalibrate the message and resend.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I move with swift momentum and clear communication.",
    symbol: "🜂",
    intentionTags: ["travel", "career", "clarity"],
  },
  {
    id: "nine-of-wands",
    number: 9,
    arcana: "minor",
    suit: "wands",
    name: "Nine of Wands",
    nameShort: "Nine of Wands",
    element: "Fire",
    astrology: "Moon",
    numerology: "Nine — resilience, persistence, the last stand.",
    keywordsUpright: ["resilience", "persistence", "last stand", "strength", "vigilance"],
    keywordsReversed: ["exhaustion", "defensiveness", "stubbornness", "burnout"],
    meaningUpright:
      "Battered but standing, the warrior grips his wand — the final test before the goal. You have come too far to falter now. Rest, then persevere; you are nearly there.",
    meaningReversed:
      "Reversed, the Nine of Wands signals burnout, defensiveness, or a wall built too thick. Lower the sword; not everyone is a threat. Restore before resuming.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I honor my resilience and rest before the final stretch.",
    symbol: "🜂",
    intentionTags: ["courage", "healing", "protection"],
  },
  {
    id: "ten-of-wands",
    number: 10,
    arcana: "minor",
    suit: "wands",
    name: "Ten of Wands",
    nameShort: "Ten of Wands",
    element: "Fire",
    astrology: "Saturn",
    numerology: "Ten — burden, completion, the weight carried too long.",
    keywordsUpright: ["burden", "responsibility", "hard work", "overload", "completion"],
    keywordsReversed: ["release", "delegation", "letting go", "recovery"],
    meaningUpright:
      "The figure struggles under a heavy load of wands, nearing the destination but nearly spent. You have taken on too much; the end is in sight. Carry what is yours; release the rest.",
    meaningReversed:
      "Reversed, the Ten of Wands signals release, delegation, or a load finally set down. The burden was never wholly yours. Breathe and lighten the path.",
    yesNoUpright: "maybe",
    yesNoReversed: "yes",
    affirmation: "I release what was never mine to carry.",
    symbol: "🜂",
    intentionTags: ["release", "healing", "career"],
  },
  {
    id: "page-of-wands",
    number: 11,
    arcana: "minor",
    suit: "wands",
    name: "Page of Wands",
    nameShort: "Page of Wands",
    element: "Fire",
    astrology: "Aries",
    numerology: "Eleven — messenger of fire, youthful exploration.",
    keywordsUpright: ["exploration", "enthusiasm", "free spirit", "messenger", "inspiration"],
    keywordsReversed: ["restlessness", "lack of direction", "delays", "scattered"],
    meaningUpright:
      "The Page holds his wand with eager wonder — a messenger of fresh fire and untested dreams. Follow the spark of curiosity; explore without needing a destination. New inspiration is arriving.",
    meaningReversed:
      "Reversed, the Page of Wands signals restlessness, scattered enthusiasm, or plans that flicker out. Choose one spark and feed it consistently.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I follow my curiosity with enthusiasm and an open heart.",
    symbol: "🜂",
    intentionTags: ["creativity", "new-beginnings", "travel"],
  },
  {
    id: "knight-of-wands",
    number: 12,
    arcana: "minor",
    suit: "wands",
    name: "Knight of Wands",
    nameShort: "Knight of Wands",
    element: "Fire",
    astrology: "Leo",
    numerology: "Twelve — quest, passion, fearless adventure.",
    keywordsUpright: ["adventure", "passion", "impulse", "energy", "fearlessness"],
    keywordsReversed: ["recklessness", "frustration", "hastiness", "scattered energy"],
    meaningUpright:
      "The Knight charges forward on a rearing horse, wand raised — pure passion in motion. Pursue your quest with fearless energy; the world makes way for the bold. Act now, refine later.",
    meaningReversed:
      "Reversed, the Knight of Wands warns of recklessness, impulsiveness, or passion burning out as fast as it flared. Slow the horse; check the direction.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I charge toward my dreams with fearless passion.",
    symbol: "🜂",
    intentionTags: ["courage", "creativity", "travel"],
  },
  {
    id: "queen-of-wands",
    number: 13,
    arcana: "minor",
    suit: "wands",
    name: "Queen of Wands",
    nameShort: "Queen of Wands",
    element: "Fire",
    astrology: "Aries",
    numerology: "Thirteen — charisma, vitality, sovereign warmth.",
    keywordsUpright: ["confidence", "charisma", "vitality", "warmth", "independence"],
    keywordsReversed: ["insecurity", "jealousy", "selfishness", "demanding"],
    meaningUpright:
      "The Queen holds her wand and her black cat with sovereign ease — vital, magnetic, unapologetically herself. Lead with warmth and confidence; your presence lights the room. Trust your power.",
    meaningReversed:
      "Reversed, the Queen of Wands signals insecurity, jealousy, or charisma turned to control. Reclaim your center before the flame turns brittle.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I lead with warmth, confidence, and sovereign presence.",
    symbol: "🜂",
    intentionTags: ["creativity", "courage", "career"],
  },
  {
    id: "king-of-wands",
    number: 14,
    arcana: "minor",
    suit: "wands",
    name: "King of Wands",
    nameShort: "King of Wands",
    element: "Fire",
    astrology: "Aries",
    numerology: "Fourteen — leadership, vision, mastery through will.",
    keywordsUpright: ["leadership", "vision", "boldness", "charisma", "mastery"],
    keywordsReversed: ["tyranny", "ruthlessness", "impulsiveness", "overbearing"],
    meaningUpright:
      "The King rules from a throne of fire and lions — vision made flesh, will made kingdom. Lead with clarity and bold conviction; others will follow your example. Mastery is yours.",
    meaningReversed:
      "Reversed, the King of Wands warns of tyranny, impulsiveness, or vision without follow-through. Lead by example, not by force.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I lead with vision, boldness, and integrity.",
    symbol: "🜂",
    intentionTags: ["career", "courage", "truth"],
  },

  // ============================================================
  // CUPS — Water 🜄
  // ============================================================
  {
    id: "ace-of-cups",
    number: 1,
    arcana: "minor",
    suit: "cups",
    name: "Ace of Cups",
    nameShort: "Ace of Cups",
    element: "Water",
    astrology: "Cancer",
    numerology: "One — genesis of feeling, the spiritual gift.",
    keywordsUpright: ["new love", "compassion", "spirituality", "intuition", "openness"],
    keywordsReversed: ["blocked emotion", "emptiness", "repressed feeling", "spiritual drift"],
    meaningUpright:
      "The cup overflows with living water, a dove descending — the gift of new love, deep feeling, or spiritual opening. Open your heart; the cup is being filled. Receive what flows toward you.",
    meaningReversed:
      "Reversed, the Ace of Cups signals blocked emotion, emotional emptiness, or a heart closing down. The well needs clearing before it can fill again.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I open my heart to love, compassion, and spiritual flow.",
    symbol: "🜄",
    intentionTags: ["love", "healing", "spiritual-growth"],
  },
  {
    id: "two-of-cups",
    number: 2,
    arcana: "minor",
    suit: "cups",
    name: "Two of Cups",
    nameShort: "Two of Cups",
    element: "Water",
    astrology: "Venus",
    numerology: "Two — partnership, mutual attraction, sacred union.",
    keywordsUpright: ["partnership", "union", "mutual attraction", "connection", "love"],
    keywordsReversed: ["imbalance", "breakup", "tension", "miscommunication"],
    meaningUpright:
      "Two figures raise their cups in shared ritual — a meeting of equals, a sacred exchange. Love, friendship, or partnership blooms where two hearts truly see each other. Honor the bond.",
    meaningReversed:
      "Reversed, the Two of Cups signals imbalance, a strained connection, or a broken trust. Examine what has tilted the exchange; restore mutuality.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I welcome partnership rooted in mutual respect and love.",
    symbol: "🜄",
    intentionTags: ["love", "family", "healing"],
  },
  {
    id: "three-of-cups",
    number: 3,
    arcana: "minor",
    suit: "cups",
    name: "Three of Cups",
    nameShort: "Three of Cups",
    element: "Water",
    astrology: "Mercury",
    numerology: "Three — celebration, friendship, the joy of community.",
    keywordsUpright: ["friendship", "celebration", "community", "joy", "abundance"],
    keywordsReversed: ["overindulgence", "gossip", "isolation", "third-party interference"],
    meaningUpright:
      "Three friends dance and raise their cups — the joy of belonging, friendship, and shared abundance. Celebrate with those who nourish you. Connection is its own wealth.",
    meaningReversed:
      "Reversed, the Three of Cups warns of overindulgence, gossip, or social fatigue. Rebalance the circle; protect your peace.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I celebrate the friendships that nourish my soul.",
    symbol: "🜄",
    intentionTags: ["family", "love", "abundance"],
  },
  {
    id: "four-of-cups",
    number: 4,
    arcana: "minor",
    suit: "cups",
    name: "Four of Cups",
    nameShort: "Four of Cups",
    element: "Water",
    astrology: "Moon",
    numerology: "Four — apathy, contemplation, re-evaluation.",
    keywordsUpright: ["apathy", "contemplation", "re-evaluation", "boredom", "ingratitude"],
    keywordsReversed: ["acceptance", "new awareness", "seizing opportunity", "awakening"],
    meaningUpright:
      "A figure sits unmoved by three cups while a fourth is offered by an unseen hand — comfort has soured into apathy. Look up; what you seek may already be reaching for you.",
    meaningReversed:
      "Reversed, the Four of Cups signals awakening, acceptance, or a new awareness breaking through the fog. The offering is seen; reach for it.",
    yesNoUpright: "maybe",
    yesNoReversed: "yes",
    affirmation: "I stay open to the gifts being offered to me.",
    symbol: "🜄",
    intentionTags: ["clarity", "healing", "release"],
  },
  {
    id: "five-of-cups",
    number: 5,
    arcana: "minor",
    suit: "cups",
    name: "Five of Cups",
    nameShort: "Five of Cups",
    element: "Water",
    astrology: "Mars",
    numerology: "Five — loss, grief, regret for what is gone.",
    keywordsUpright: ["loss", "grief", "regret", "disappointment", "focus on what's lost"],
    keywordsReversed: ["acceptance", "recovery", "moving on", "forgiveness"],
    meaningUpright:
      "A figure mourns three spilled cups while two stand full behind him — grief narrows the view to what is gone. Honor the loss, then turn; some cups remain. Healing waits in the turn.",
    meaningReversed:
      "Reversed, the Five of Cups signals recovery, acceptance, or moving on from loss. The full cups return to view. Forgive and step forward.",
    yesNoUpright: "no",
    yesNoReversed: "maybe",
    affirmation: "I honor my grief and turn toward what remains.",
    symbol: "🜄",
    intentionTags: ["healing", "release", "family"],
  },
  {
    id: "six-of-cups",
    number: 6,
    arcana: "minor",
    suit: "cups",
    name: "Six of Cups",
    nameShort: "Six of Cups",
    element: "Water",
    astrology: "Sun",
    numerology: "Six — nostalgia, innocence, the kindness of memory.",
    keywordsUpright: ["nostalgia", "innocence", "childhood", "reunion", "kindness"],
    keywordsReversed: ["clinging to past", "stuck", "unrealistic nostalgia", "moving forward"],
    meaningUpright:
      "Two children share flowers in a garden — a tender memory, a return to innocence, a kindness offered freely. Reconnect with what nourished your younger self. Sweetness is its own medicine.",
    meaningReversed:
      "Reversed, the Six of Cups warns of clinging to the past, idealizing what was, or staying stuck in nostalgia. Honor memory; release its hold.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I honor my past while living fully in the present.",
    symbol: "🜄",
    intentionTags: ["family", "healing", "love"],
  },
  {
    id: "seven-of-cups",
    number: 7,
    arcana: "minor",
    suit: "cups",
    name: "Seven of Cups",
    nameShort: "Seven of Cups",
    element: "Water",
    astrology: "Venus",
    numerology: "Seven — illusion, fantasy, the danger of too many choices.",
    keywordsUpright: ["fantasy", "choices", "illusion", "imagination", "temptation"],
    keywordsReversed: ["clarity", "decision", "reality check", "focus"],
    meaningUpright:
      "Seven cups float, each holding a different dream — fantasy, temptation, the danger of too many choices. Beautiful visions, but which is real? Choose with discernment, not longing.",
    meaningReversed:
      "Reversed, the Seven of Cups signals clarity returning, a decision made, or illusions dispelled. The mist clears. Commit to the true path.",
    yesNoUpright: "maybe",
    yesNoReversed: "yes",
    affirmation: "I see through illusion and choose with clarity.",
    symbol: "🜄",
    intentionTags: ["clarity", "creativity", "truth"],
  },
  {
    id: "eight-of-cups",
    number: 8,
    arcana: "minor",
    suit: "cups",
    name: "Eight of Cups",
    nameShort: "Eight of Cups",
    element: "Water",
    astrology: "Saturn",
    numerology: "Eight — leaving, seeking deeper meaning, walking away.",
    keywordsUpright: ["walking away", "seeking", "spiritual quest", "leaving behind", "disillusionment"],
    keywordsReversed: ["fear of change", "returning", "wandering", "avoidance"],
    meaningUpright:
      "The figure turns from eight stacked cups to walk into the mountains under an eclipsed moon — enough is not enough. You seek a deeper fulfillment than this. Honor the courage to leave.",
    meaningReversed:
      "Reversed, the Eight of Cups signals fear of leaving, wandering without arrival, or returning to what didn't fit. Be honest about what you seek.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I have the courage to seek what truly fulfills me.",
    symbol: "🜄",
    intentionTags: ["spiritual-growth", "release", "transformation"],
  },
  {
    id: "nine-of-cups",
    number: 9,
    arcana: "minor",
    suit: "cups",
    name: "Nine of Cups",
    nameShort: "Nine of Cups",
    element: "Water",
    astrology: "Jupiter",
    numerology: "Nine — satisfaction, contentment, the wish fulfilled.",
    keywordsUpright: ["contentment", "satisfaction", "wish fulfilled", "pleasure", "abundance"],
    keywordsReversed: ["dissatisfaction", "overindulgence", "shallowness", "unfulfilled"],
    meaningUpright:
      "The satisfied figure sits before his nine cups, smiling — the wish card, the smile of fulfilled desire. Pleasure and contentment are yours. Savor them; share them when ready.",
    meaningReversed:
      "Reversed, the Nine of Cups signals dissatisfaction, shallowness, or wishes that didn't deliver. Look beyond the surface; what do you truly want?",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I savor the fulfillment of my heart's true wishes.",
    symbol: "🜄",
    intentionTags: ["abundance", "healing", "love"],
  },
  {
    id: "ten-of-cups",
    number: 10,
    arcana: "minor",
    suit: "cups",
    name: "Ten of Cups",
    nameShort: "Ten of Cups",
    element: "Water",
    astrology: "Mars",
    numerology: "Ten — emotional fulfillment, harmony, family wholeness.",
    keywordsUpright: ["harmony", "family", "joy", "alignment", "emotional fulfillment"],
    keywordsReversed: ["misalignment", "broken home", "conflict", "disconnection"],
    meaningUpright:
      "A family rejoices under a rainbow of ten cups — the emotional harvest, alignment of heart and home. Joy rooted in shared values blooms. Savor this; you have built it.",
    meaningReversed:
      "Reversed, the Ten of Cups signals misalignment, disconnection, or family strain. The rainbow dims but does not vanish. Reconnect heart to heart.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I nurture harmony and joy in my home and heart.",
    symbol: "🜄",
    intentionTags: ["family", "love", "abundance"],
  },
  {
    id: "page-of-cups",
    number: 11,
    arcana: "minor",
    suit: "cups",
    name: "Page of Cups",
    nameShort: "Page of Cups",
    element: "Water",
    astrology: "Cancer",
    numerology: "Eleven — messenger of feeling, wonder, gentle beginnings.",
    keywordsUpright: ["creative message", "intuition", "wonder", "sensitivity", "gentle beginnings"],
    keywordsReversed: ["escapism", "immaturity", "emotional avoidance", "oversensitivity"],
    meaningUpright:
      "The Page looks with wonder at a fish popping from his cup — a tender message from the unconscious, a creative spark dressed in dream. Listen to the small, strange voice. Sweetness is arriving.",
    meaningReversed:
      "Reversed, the Page of Cups signals emotional immaturity, escapism, or sensitivity turned to avoidance. Grow gently; face what you feel.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I listen to the small, creative voice within me.",
    symbol: "🜄",
    intentionTags: ["creativity", "intuition", "love"],
  },
  {
    id: "knight-of-cups",
    number: 12,
    arcana: "minor",
    suit: "cups",
    name: "Knight of Cups",
    nameShort: "Knight of Cups",
    element: "Water",
    astrology: "Pisces",
    numerology: "Twelve — quest of the heart, romance, idealism.",
    keywordsUpright: ["romance", "ideals", "imagination", "charm", "following the heart"],
    keywordsReversed: ["moodiness", "unrealistic", "disappointment", "emotional turbulence"],
    meaningUpright:
      "The Knight rides forward bearing a cup of love, dreamer and romantic quester. Follow what stirs your heart; offer your beauty to the world. Charm and sincerity move mountains.",
    meaningReversed:
      "Reversed, the Knight of Cups signals moodiness, unrealistic idealism, or promises unkept. Ground the dream in real action.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I follow the call of my heart with grace and sincerity.",
    symbol: "🜄",
    intentionTags: ["love", "creativity", "spiritual-growth"],
  },
  {
    id: "queen-of-cups",
    number: 13,
    arcana: "minor",
    suit: "cups",
    name: "Queen of Cups",
    nameShort: "Queen of Cups",
    element: "Water",
    astrology: "Cancer",
    numerology: "Thirteen — receptivity, compassion, emotional mastery.",
    keywordsUpright: ["compassion", "calm", "intuition", "receptivity", "emotional security"],
    keywordsReversed: ["co-dependency", "emotional overwhelm", "insecurity", "martyrdom"],
    meaningUpright:
      "The Queen's cup is closed with sculpted angels — she holds feeling without being consumed by it. Receive the world with compassion and clear boundaries. Your intuition is a steady river.",
    meaningReversed:
      "Reversed, the Queen of Cups signals emotional overwhelm, codependency, or waters muddied by others' feelings. Re-anchor in your own cup.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I hold my feelings with compassion and clear boundaries.",
    symbol: "🜄",
    intentionTags: ["healing", "intuition", "love"],
  },
  {
    id: "king-of-cups",
    number: 14,
    arcana: "minor",
    suit: "cups",
    name: "King of Cups",
    nameShort: "King of Cups",
    element: "Water",
    astrology: "Scorpio",
    numerology: "Fourteen — emotional mastery, balance, diplomacy.",
    keywordsUpright: ["emotional balance", "diplomacy", "calm", "compassion", "wisdom"],
    keywordsReversed: ["manipulation", "volatility", "coldness", "moodiness"],
    meaningUpright:
      "The King sits calm on his throne amid roiling sea — master of feeling, not slave to it. Lead with compassion and steadiness; others find harbor in you. Balance is your power.",
    meaningReversed:
      "Reversed, the King of Cups warns of emotional manipulation, coldness, or volatility masked as calm. Restore the inner harbor before you lead.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I lead with calm, compassionate mastery of my heart.",
    symbol: "🜄",
    intentionTags: ["healing", "family", "truth"],
  },

  // ============================================================
  // SWORDS — Air 🜁
  // ============================================================
  {
    id: "ace-of-swords",
    number: 1,
    arcana: "minor",
    suit: "swords",
    name: "Ace of Swords",
    nameShort: "Ace of Swords",
    element: "Air",
    astrology: "Gemini",
    numerology: "One — clarity, breakthrough, mental genesis.",
    keywordsUpright: ["clarity", "breakthrough", "truth", "new idea", "sharp focus"],
    keywordsReversed: ["confusion", "clouded judgment", "poor communication", "chaos"],
    meaningUpright:
      "A single sword rises crowned — the cut of clarity, the breakthrough of truth. A new idea pierces confusion. Speak and act with sharp honesty now.",
    meaningReversed:
      "Reversed, the Ace of Swords signals confusion, clouded judgment, or communication breaking down. The cut must be sharpened before it can clear.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I cut through confusion with the sword of clear truth.",
    symbol: "🜁",
    intentionTags: ["clarity", "truth", "courage"],
  },
  {
    id: "two-of-swords",
    number: 2,
    arcana: "minor",
    suit: "swords",
    name: "Two of Swords",
    nameShort: "Two of Swords",
    element: "Air",
    astrology: "Moon",
    numerology: "Two — stalemate, indecision, the blindfolded choice.",
    keywordsUpright: ["indecision", "stalemate", "blocked emotions", "choices", "truce"],
    keywordsReversed: ["decision", "clarity", "release", "information revealed"],
    meaningUpright:
      "A blindfolded figure crosses two swords — a stalemate between heart and mind, an avoided choice. The truth cannot stay hidden forever. Remove the blindfold when you are ready.",
    meaningReversed:
      "Reversed, the Two of Swords signals a decision made, information revealed, or a stalemate breaking. Clarity returns as the blindfold falls.",
    yesNoUpright: "maybe",
    yesNoReversed: "yes",
    affirmation: "I face my choices with clear eyes and a calm heart.",
    symbol: "🜁",
    intentionTags: ["clarity", "truth", "release"],
  },
  {
    id: "three-of-swords",
    number: 3,
    arcana: "minor",
    suit: "swords",
    name: "Three of Swords",
    nameShort: "Three of Swords",
    element: "Air",
    astrology: "Saturn",
    numerology: "Three — sorrow, heartbreak, the painful truth.",
    keywordsUpright: ["heartbreak", "sorrow", "painful truth", "grief", "betrayal"],
    keywordsReversed: ["healing", "forgiveness", "recovery", "releasing pain"],
    meaningUpright:
      "Three swords pierce a heart under rain — sorrow, heartbreak, the truth that hurts. Let the pain move; the rain will stop. What is broken can be mended softer.",
    meaningReversed:
      "Reversed, the Three of Swords signals healing, forgiveness, or pain finally releasing. The storm passes. Let the heart open again, gently.",
    yesNoUpright: "no",
    yesNoReversed: "yes",
    affirmation: "I allow my sorrow to move and my heart to heal.",
    symbol: "🜁",
    intentionTags: ["healing", "release", "love"],
  },
  {
    id: "four-of-swords",
    number: 4,
    arcana: "minor",
    suit: "swords",
    name: "Four of Swords",
    nameShort: "Four of Swords",
    element: "Air",
    astrology: "Jupiter",
    numerology: "Four — rest, recovery, sacred contemplation.",
    keywordsUpright: ["rest", "recovery", "contemplation", "stillness", "retreat"],
    keywordsReversed: ["restlessness", "burnout", "reawakening", "stagnation"],
    meaningUpright:
      "A knight rests in a tomb beneath three swords, one beneath him — deliberate stillness, sacred recovery. Pause and recharge; the world will wait. Rest is part of the work.",
    meaningReversed:
      "Reversed, the Four of Swords signals restlessness, burnout, or an end to the needed rest. Reawaken slowly; do not leap before you are ready.",
    yesNoUpright: "maybe",
    yesNoReversed: "yes",
    affirmation: "I honor rest as a sacred part of my growth.",
    symbol: "🜁",
    intentionTags: ["healing", "spiritual-growth", "clarity"],
  },
  {
    id: "five-of-swords",
    number: 5,
    arcana: "minor",
    suit: "swords",
    name: "Five of Swords",
    nameShort: "Five of Swords",
    element: "Air",
    astrology: "Venus",
    numerology: "Five — conflict, defeat, the hollow victory.",
    keywordsUpright: ["conflict", "defeat", "winning at all costs", "loss", "tension"],
    keywordsReversed: ["reconciliation", "release", "forgiveness", "moving on"],
    meaningUpright:
      "The victor gathers swords while others walk away defeated — but at what cost? Some wins are hollow. Choose your battles; not every victory is worth its price.",
    meaningReversed:
      "Reversed, the Five of Swords signals reconciliation, release, or moving on from a costly conflict. Lay down the sword; seek the deeper win.",
    yesNoUpright: "no",
    yesNoReversed: "maybe",
    affirmation: "I release the need to win at any cost and choose peace.",
    symbol: "🜁",
    intentionTags: ["release", "clarity", "truth"],
  },
  {
    id: "six-of-swords",
    number: 6,
    arcana: "minor",
    suit: "swords",
    name: "Six of Swords",
    nameShort: "Six of Swords",
    element: "Air",
    astrology: "Mercury",
    numerology: "Six — transition, movement, calmer waters ahead.",
    keywordsUpright: ["transition", "moving on", "recovery", "journey", "calmer waters"],
    keywordsReversed: ["resistance", "stuck", "avoidance", "unfinished business"],
    meaningUpright:
      "A mother and child are ferried across still water toward a distant shore — leaving turbulence behind, moving toward calmer ground. The journey is hard but right. Trust the passage.",
    meaningReversed:
      "Reversed, the Six of Swords signals resistance to moving on, unfinished business, or a stalled passage. You cannot carry everything across. Choose what to leave.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I move toward calmer waters with trust and grace.",
    symbol: "🜁",
    intentionTags: ["release", "healing", "travel"],
  },
  {
    id: "seven-of-swords",
    number: 7,
    arcana: "minor",
    suit: "swords",
    name: "Seven of Swords",
    nameShort: "Seven of Swords",
    element: "Air",
    astrology: "Moon",
    numerology: "Seven — strategy, stealth, deception.",
    keywordsUpright: ["strategy", "stealth", "cunning", "deception", "independence"],
    keywordsReversed: ["confession", "coming clean", "exposure", "returning"],
    meaningUpright:
      "A figure sneaks off with five swords, leaving two behind — strategy, stealth, or someone acting in secret. Not all is as it appears. Move carefully and protect what is yours.",
    meaningReversed:
      "Reversed, the Seven of Swords signals secrets revealed, confessions made, or a return of what was taken. Honesty restores the balance.",
    yesNoUpright: "no",
    yesNoReversed: "maybe",
    affirmation: "I act with integrity and meet secrecy with clear seeing.",
    symbol: "🜁",
    intentionTags: ["protection", "truth", "clarity"],
  },
  {
    id: "eight-of-swords",
    number: 8,
    arcana: "minor",
    suit: "swords",
    name: "Eight of Swords",
    nameShort: "Eight of Swords",
    element: "Air",
    astrology: "Jupiter",
    numerology: "Eight — restriction, the self-imposed prison, fear.",
    keywordsUpright: ["restriction", "feeling trapped", "self-imposed limits", "fear", "isolation"],
    keywordsReversed: ["release", "self-liberation", "new perspective", "openness"],
    meaningUpright:
      "A blindfolded figure stands bound among eight swords — but the bonds are loose, the path open if she would only see. The prison is woven of belief. Loosen the blindfold.",
    meaningReversed:
      "Reversed, the Eight of Swords signals self-liberation, a new perspective, or chains falling away. You see the opening at last. Step through.",
    yesNoUpright: "no",
    yesNoReversed: "yes",
    affirmation: "I release the limits I placed upon myself.",
    symbol: "🜁",
    intentionTags: ["release", "clarity", "healing"],
  },
  {
    id: "nine-of-swords",
    number: 9,
    arcana: "minor",
    suit: "swords",
    name: "Nine of Swords",
    nameShort: "Nine of Swords",
    element: "Air",
    astrology: "Mars",
    numerology: "Nine — anxiety, nightmare, the mind feeding its fears.",
    keywordsUpright: ["anxiety", "nightmare", "worry", "grief", "fear"],
    keywordsReversed: ["hope", "recovery", "release of fear", "facing truth"],
    meaningUpright:
      "A figure wakes in despair, nine swords on the wall — anxiety, nightmares, the mind feeding its own fears. The dread is real but largely imagined. Reach for the light; speak the fear.",
    meaningReversed:
      "Reversed, the Nine of Swords signals hope, recovery, or fears releasing their grip. The nightmare ends with the dawn. Reach for help.",
    yesNoUpright: "no",
    yesNoReversed: "yes",
    affirmation: "I release the anxieties that haunted my nights.",
    symbol: "🜁",
    intentionTags: ["healing", "release", "clarity"],
  },
  {
    id: "ten-of-swords",
    number: 10,
    arcana: "minor",
    suit: "swords",
    name: "Ten of Swords",
    nameShort: "Ten of Swords",
    element: "Air",
    astrology: "Sun",
    numerology: "Ten — ending, rock bottom, the dawn after the dark.",
    keywordsUpright: ["ending", "rock bottom", "betrayal", "painful closure", "collapse"],
    keywordsReversed: ["recovery", "survival", "renewal", "worst is over"],
    meaningUpright:
      "A figure lies pierced by ten swords under a dawning sky — the end, the rock bottom, the betrayal complete. But the sun is rising. What is finished cannot hurt you further. Begin again.",
    meaningReversed:
      "Reversed, the Ten of Swords signals recovery, survival, the worst finally over. The dawn has come. Rise and walk forward.",
    yesNoUpright: "no",
    yesNoReversed: "yes",
    affirmation: "I have survived the worst and welcome the new dawn.",
    symbol: "🜁",
    intentionTags: ["release", "transformation", "healing"],
  },
  {
    id: "page-of-swords",
    number: 11,
    arcana: "minor",
    suit: "swords",
    name: "Page of Swords",
    nameShort: "Page of Swords",
    element: "Air",
    astrology: "Gemini",
    numerology: "Eleven — messenger of mind, curiosity, vigilance.",
    keywordsUpright: ["curiosity", "new ideas", "vigilance", "messenger", "mental agility"],
    keywordsReversed: ["deception", "gossip", "hastiness", "scattered thought"],
    meaningUpright:
      "The Page raises his sword amid windblown clouds — curiosity, fresh thought, the hunger to know. Stay curious; ask the sharp question. New information is arriving.",
    meaningReversed:
      "Reversed, the Page of Swords signals gossip, deception, or scattered thinking. Sharpen the mind before speaking.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I stay curious and ask the questions that reveal truth.",
    symbol: "🜁",
    intentionTags: ["clarity", "truth", "creativity"],
  },
  {
    id: "knight-of-swords",
    number: 12,
    arcana: "minor",
    suit: "swords",
    name: "Knight of Swords",
    nameShort: "Knight of Swords",
    element: "Air",
    astrology: "Aquarius",
    numerology: "Twelve — swift action, ambition, the single-minded charge.",
    keywordsUpright: ["ambition", "drive", "fast action", "directness", "boldness"],
    keywordsReversed: ["impulsiveness", "recklessness", "burnout", "no direction"],
    meaningUpright:
      "The Knight charges full-tilt, sword raised — single-minded drive, swift action, ambition in motion. Pursue the goal with conviction. Just check the destination.",
    meaningReversed:
      "Reversed, the Knight of Swords warns of recklessness, impulsiveness, or charging without a plan. Slow the horse; aim first.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I act swiftly and decisively on what I know to be true.",
    symbol: "🜁",
    intentionTags: ["courage", "career", "clarity"],
  },
  {
    id: "queen-of-swords",
    number: 13,
    arcana: "minor",
    suit: "swords",
    name: "Queen of Swords",
    nameShort: "Queen of Swords",
    element: "Air",
    astrology: "Libra",
    numerology: "Thirteen — sharp discernment, independence, clear truth.",
    keywordsUpright: ["discernment", "independence", "clarity", "directness", "wisdom"],
    keywordsReversed: ["coldness", "cruelty", "bitterness", "judgment"],
    meaningUpright:
      "The Queen raises her sword with a clear, steady gaze — discernment honed by experience, independence earned. Speak the truth with compassion; cut what no longer serves. Wisdom is your blade.",
    meaningReversed:
      "Reversed, the Queen of Swords warns of coldness, bitterness, or sharp words that wound. Soften the blade with heart.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I speak my truth with clarity, compassion, and independence.",
    symbol: "🜁",
    intentionTags: ["truth", "clarity", "courage"],
  },
  {
    id: "king-of-swords",
    number: 14,
    arcana: "minor",
    suit: "swords",
    name: "King of Swords",
    nameShort: "King of Swords",
    element: "Air",
    astrology: "Aquarius",
    numerology: "Fourteen — authority, intellect, truth as sovereignty.",
    keywordsUpright: ["authority", "truth", "intellect", "clarity", "leadership"],
    keywordsReversed: ["manipulation", "tyranny", "abuse of power", "coldness"],
    meaningUpright:
      "The King holds his sword upright with calm command — intellect in service of justice, truth as sovereignty. Lead with clear thought and ethical clarity. Your word carries weight.",
    meaningReversed:
      "Reversed, the King of Swords warns of manipulation, tyranny, or intellect weaponized. Restore integrity to your authority.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I lead with clear mind, integrity, and truthful authority.",
    symbol: "🜁",
    intentionTags: ["truth", "clarity", "career"],
  },

  // ============================================================
  // PENTACLES — Earth 🜃
  // ============================================================
  {
    id: "ace-of-pentacles",
    number: 1,
    arcana: "minor",
    suit: "pentacles",
    name: "Ace of Pentacles",
    nameShort: "Ace of Pentacles",
    element: "Earth",
    astrology: "Taurus",
    numerology: "One — new opportunity, prosperity, manifestation in form.",
    keywordsUpright: ["opportunity", "prosperity", "new venture", "manifestation", "abundance"],
    keywordsReversed: ["missed opportunity", "scarcity", "poor planning", "setback"],
    meaningUpright:
      "A single coin glows in a fertile garden — a new opportunity, an investment, prosperity taking root. Accept the gift and plant it well. What you begin now will grow.",
    meaningReversed:
      "Reversed, the Ace of Pentacles signals a missed opportunity, scarcity, or plans that don't take root. Tend the soil before sowing again.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I welcome new opportunities for abundance and growth.",
    symbol: "🜃",
    intentionTags: ["abundance", "career", "new-beginnings"],
  },
  {
    id: "two-of-pentacles",
    number: 2,
    arcana: "minor",
    suit: "pentacles",
    name: "Two of Pentacles",
    nameShort: "Two of Pentacles",
    element: "Earth",
    astrology: "Jupiter",
    numerology: "Two — balance, juggling, adaptability.",
    keywordsUpright: ["balance", "juggling", "adaptability", "flexibility", "priorities"],
    keywordsReversed: ["imbalance", "overwhelm", "disorganization", "overcommitted"],
    meaningUpright:
      "A figure juggles two coins amid tossing waves — many demands, balanced with grace and flexibility. Stay light on your feet; you can hold it all if you keep moving. Prioritize as you go.",
    meaningReversed:
      "Reversed, the Two of Pentacles signals overwhelm, imbalance, or too many plates spinning. Set something down before it falls.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I balance my commitments with flexibility and grace.",
    symbol: "🜃",
    intentionTags: ["career", "abundance", "clarity"],
  },
  {
    id: "three-of-pentacles",
    number: 3,
    arcana: "minor",
    suit: "pentacles",
    name: "Three of Pentacles",
    nameShort: "Three of Pentacles",
    element: "Earth",
    astrology: "Mars",
    numerology: "Three — collaboration, mastery, building together.",
    keywordsUpright: ["teamwork", "collaboration", "craft", "skill", "building"],
    keywordsReversed: ["disharmony", "misalignment", "poor teamwork", "mediocrity"],
    meaningUpright:
      "An artisan consults with monk and architect before a cathedral arch — collaboration, mastery, craft in service of something larger. Combine your gifts with others'. Great work is built together.",
    meaningReversed:
      "Reversed, the Three of Pentacles signals team disharmony, misalignment, or work beneath your standards. Realign on the blueprint before building further.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I collaborate with skill and shared purpose.",
    symbol: "🜃",
    intentionTags: ["career", "creativity", "abundance"],
  },
  {
    id: "four-of-pentacles",
    number: 4,
    arcana: "minor",
    suit: "pentacles",
    name: "Four of Pentacles",
    nameShort: "Four of Pentacles",
    element: "Earth",
    astrology: "Sun",
    numerology: "Four — security, control, holding on tight.",
    keywordsUpright: ["security", "control", "saving", "holding", "stability"],
    keywordsReversed: ["letting go", "greed", "loosening control", "material loss"],
    meaningUpright:
      "A figure clutches four coins — crown, heart, foot, and the one before him — security hard-won, sometimes hoarded. Stability matters; so does flow. Hold what you need; release what you don't.",
    meaningReversed:
      "Reversed, the Four of Pentacles signals loosening grip, generosity returning, or material loss teaching impermanence. Open the hand; abundance flows.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I hold my resources with wisdom and open hands.",
    symbol: "🜃",
    intentionTags: ["abundance", "release", "protection"],
  },
  {
    id: "five-of-pentacles",
    number: 5,
    arcana: "minor",
    suit: "pentacles",
    name: "Five of Pentacles",
    nameShort: "Five of Pentacles",
    element: "Earth",
    astrology: "Mercury",
    numerology: "Five — hardship, scarcity, the help just out of reach.",
    keywordsUpright: ["hardship", "scarcity", "exclusion", "struggle", "need"],
    keywordsReversed: ["recovery", "aid", "improvement", "returning warmth"],
    meaningUpright:
      "Two figures stumble in the snow past a lit church window — hardship, scarcity, the help just out of reach. The door is open; you have not been abandoned. Seek the warmth you need.",
    meaningReversed:
      "Reversed, the Five of Pentacles signals recovery, aid arriving, or hardship easing. The door opens; the fire warms. Accept the help offered.",
    yesNoUpright: "no",
    yesNoReversed: "yes",
    affirmation: "I am willing to receive the help and warmth I need.",
    symbol: "🜃",
    intentionTags: ["healing", "abundance", "release"],
  },
  {
    id: "six-of-pentacles",
    number: 6,
    arcana: "minor",
    suit: "pentacles",
    name: "Six of Pentacles",
    nameShort: "Six of Pentacles",
    element: "Earth",
    astrology: "Moon",
    numerology: "Six — generosity, fair exchange, balanced giving.",
    keywordsUpright: ["generosity", "charity", "fairness", "exchange", "giving and receiving"],
    keywordsReversed: ["imbalance", "strings attached", "selfishness", "debt"],
    meaningUpright:
      "A merchant weighs coins in one hand and gives with the other — generosity in balance, fair exchange. Give what you can; receive what you need. True wealth circulates.",
    meaningReversed:
      "Reversed, the Six of Pentacles signals imbalance in giving, strings attached, or generosity that impoverishes. Recalibrate the scales.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I give and receive in harmonious balance.",
    symbol: "🜃",
    intentionTags: ["abundance", "family", "healing"],
  },
  {
    id: "seven-of-pentacles",
    number: 7,
    arcana: "minor",
    suit: "pentacles",
    name: "Seven of Pentacles",
    nameShort: "Seven of Pentacles",
    element: "Earth",
    astrology: "Saturn",
    numerology: "Seven — patience, assessment, slow growth.",
    keywordsUpright: ["patience", "assessment", "slow growth", "investment", "waiting"],
    keywordsReversed: ["frustration", "wasted effort", "impatience", "poor return"],
    meaningUpright:
      "A farmer leans on his hoe, surveying six coins growing on the vine — patient labor, slow return, assessment at the midpoint. The harvest is forming; trust the work. Tend what is growing.",
    meaningReversed:
      "Reversed, the Seven of Pentacles signals frustration, wasted effort, or returns too slow. Reassess; perhaps the crop or the soil needs changing.",
    yesNoUpright: "maybe",
    yesNoReversed: "no",
    affirmation: "I trust the slow growth of what I am tending.",
    symbol: "🜃",
    intentionTags: ["abundance", "career", "healing"],
  },
  {
    id: "eight-of-pentacles",
    number: 8,
    arcana: "minor",
    suit: "pentacles",
    name: "Eight of Pentacles",
    nameShort: "Eight of Pentacles",
    element: "Earth",
    astrology: "Sun",
    numerology: "Eight — mastery, craft, devotion to skill.",
    keywordsUpright: ["mastery", "craft", "dedication", "skill", "apprenticeship"],
    keywordsReversed: ["perfectionism", "lack of focus", "boredom", "scattered"],
    meaningUpright:
      "The apprentice hammers coin after coin, focused and dedicated — mastery through devotion to craft. Hone your skill; the work itself is the reward. Excellence grows with practice.",
    meaningReversed:
      "Reversed, the Eight of Pentacles warns of perfectionism, boredom, or work without joy. Reconnect to why you began; let craft become craft again.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I dedicate myself to my craft with focus and joy.",
    symbol: "🜃",
    intentionTags: ["career", "creativity", "abundance"],
  },
  {
    id: "nine-of-pentacles",
    number: 9,
    arcana: "minor",
    suit: "pentacles",
    name: "Nine of Pentacles",
    nameShort: "Nine of Pentacles",
    element: "Earth",
    astrology: "Venus",
    numerology: "Nine — self-sufficiency, refinement, abundance earned.",
    keywordsUpright: ["self-sufficiency", "abundance", "refinement", "luxury", "independence"],
    keywordsReversed: ["over-investment in work", "superficiality", "dependence", "loss"],
    meaningUpright:
      "A woman walks in her vineyard, falcon on her wrist — the harvest of disciplined effort, abundance earned and savored. Enjoy what you have cultivated; your independence is beautiful.",
    meaningReversed:
      "Reversed, the Nine of Pentacles signals overwork, superficiality, or worth tied too tightly to material. Reconnect to the deeper value beneath the harvest.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I savor the abundance my discipline has cultivated.",
    symbol: "🜃",
    intentionTags: ["abundance", "career", "healing"],
  },
  {
    id: "ten-of-pentacles",
    number: 10,
    arcana: "minor",
    suit: "pentacles",
    name: "Ten of Pentacles",
    nameShort: "Ten of Pentacles",
    element: "Earth",
    astrology: "Mercury",
    numerology: "Ten — legacy, family wealth, the lasting foundation.",
    keywordsUpright: ["legacy", "family", "wealth", "stability", "generational"],
    keywordsReversed: ["financial failure", "family conflict", "instability", "loss of legacy"],
    meaningUpright:
      "Three generations gather beneath arches of pentacles — legacy, family wealth, foundations built to last. Honor what has been passed down; tend what you will leave behind. Build for the long view.",
    meaningReversed:
      "Reversed, the Ten of Pentacles signals family conflict, financial loss, or a legacy fraying at the edges. Restore the foundation before it crumbles further.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I tend my legacy and build for generations to come.",
    symbol: "🜃",
    intentionTags: ["family", "abundance", "protection"],
  },
  {
    id: "page-of-pentacles",
    number: 11,
    arcana: "minor",
    suit: "pentacles",
    name: "Page of Pentacles",
    nameShort: "Page of Pentacles",
    element: "Earth",
    astrology: "Taurus",
    numerology: "Eleven — student, study, the seed of new beginnings.",
    keywordsUpright: ["study", "new venture", "curiosity", "manifestation", "student"],
    keywordsReversed: ["lack of progress", "procrastination", "scattered study", "unfocused"],
    meaningUpright:
      "The Page gazes with reverence at his coin — the student, the apprentice, the dreamer of new beginnings. Commit to learning; the seed is in your hand. Devotion will make it grow.",
    meaningReversed:
      "Reversed, the Page of Pentacles signals procrastination, scattered focus, or lessons unlearned. Pick up the coin and study it again.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I am a devoted student of my unfolding life.",
    symbol: "🜃",
    intentionTags: ["new-beginnings", "career", "abundance"],
  },
  {
    id: "knight-of-pentacles",
    number: 12,
    arcana: "minor",
    suit: "pentacles",
    name: "Knight of Pentacles",
    nameShort: "Knight of Pentacles",
    element: "Earth",
    astrology: "Virgo",
    numerology: "Twelve — diligence, routine, steady effort.",
    keywordsUpright: ["diligence", "routine", "hard work", "reliability", "patience"],
    keywordsReversed: ["stagnation", "boredom", "perfectionism", "laziness"],
    meaningUpright:
      "The Knight rides his steady plow-horse, coin in hand, never rushing — diligence, routine, the long reliable road. Keep showing up. Slow and steady finishes what flash cannot.",
    meaningReversed:
      "Reversed, the Knight of Pentacles signals stagnation, boredom, or work become joyless. Shake the routine; reconnect to the why.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I show up with diligence and steady devotion to my path.",
    symbol: "🜃",
    intentionTags: ["career", "abundance", "courage"],
  },
  {
    id: "queen-of-pentacles",
    number: 13,
    arcana: "minor",
    suit: "pentacles",
    name: "Queen of Pentacles",
    nameShort: "Queen of Pentacles",
    element: "Earth",
    astrology: "Taurus",
    numerology: "Thirteen — nurturing abundance, grounded care.",
    keywordsUpright: ["nurturing", "practical", "abundance", "grounded", "warmth"],
    keywordsReversed: ["self-neglect", "smothering", "work-life imbalance", "insecurity"],
    meaningUpright:
      "The Queen sits on her throne amid blooming earth, coin in her lap — grounded care, practical abundance, mother of the harvest. Tend yourself and your world with steady hands. Nourishment flows.",
    meaningReversed:
      "Reversed, the Queen of Pentacles signals self-neglect, smothering care, or work-life out of balance. Pour from a full cup; refill your own.",
    yesNoUpright: "yes",
    yesNoReversed: "maybe",
    affirmation: "I nurture myself and others from a place of grounded abundance.",
    symbol: "🜃",
    intentionTags: ["family", "abundance", "healing"],
  },
  {
    id: "king-of-pentacles",
    number: 14,
    arcana: "minor",
    suit: "pentacles",
    name: "King of Pentacles",
    nameShort: "King of Pentacles",
    element: "Earth",
    astrology: "Taurus",
    numerology: "Fourteen — mastery of the material, abundance, legacy.",
    keywordsUpright: ["abundance", "mastery", "stability", "prosperity", "leadership"],
    keywordsReversed: ["greed", "control", "materialism", "stagnation"],
    meaningUpright:
      "The King sits enthroned amid ripe vineyards, coin and orb in hand — mastery of the material world, prosperity earned and shared. Build generously; lead with grounded authority. Your kingdom is real.",
    meaningReversed:
      "Reversed, the King of Pentacles warns of greed, control, or worth reduced to wealth. Re-anchor abundance in service and stewardship.",
    yesNoUpright: "yes",
    yesNoReversed: "no",
    affirmation: "I steward abundance with mastery, generosity, and care.",
    symbol: "🜃",
    intentionTags: ["abundance", "career", "family"],
  },
];

// ============================================================
// Helper functions
// ============================================================

/** Returns the card with the given id slug, or undefined. */
export function getCardById(id: string): TarotCard | undefined {
  return TAROT_DECK.find((c) => c.id === id);
}

/** Returns all 78 cards in the deck. */
export function getAllCards(): TarotCard[] {
  return TAROT_DECK;
}

/** Returns the 22 Major Arcana cards (Fool through World). */
export function getMajorArcana(): TarotCard[] {
  return TAROT_DECK.filter((c) => c.arcana === "major");
}

/** Returns the 56 Minor Arcana cards (Wands, Cups, Swords, Pentacles). */
export function getMinorArcana(): TarotCard[] {
  return TAROT_DECK.filter((c) => c.arcana === "minor");
}

/** Returns all cards whose intentionTags include the given tag. */
export function getCardsByIntention(tag: string): TarotCard[] {
  return TAROT_DECK.filter((c) => c.intentionTags.includes(tag));
}
